### PR TITLE
make commands callable by Artisan::call

### PR DESCRIPTION
**Pull request by tanmuhittin**
I need this in this package: https://github.com/tanmuhittin/laravel-lang-publisher

### CODE REVIEW

**Comment by andrey-helldar** [comment]
When do you want to use the `Artisan::call()` method?

**Comment by tanmuhittin** [comment]
Sorry about my previous comment. I added wrong link. I am preparing a PR to 

https://github.com/barryvdh/laravel-translation-manager

It is almost finished : https://github.com/tanmuhittin/laravel-translation-manager
With this PR new locales can be added with translations using this package for base files and that package for custom translation files:
https://github.com/tanmuhittin/laravel-google-translate
This is the exact place Artisan::call is used : https://github.com/tanmuhittin/laravel-translation-manager/blob/05bbae4905a0e73978758286932ed71eb80172f2/src/Controller.php#L174

Waiting for your merge to publish the PR https://github.com/tanmuhittin/laravel-translation-manager

**Comment by andrey-helldar** [comment]
Released https://github.com/andrey-helldar/laravel-lang-publisher/releases/tag/v1.2.0

**Comment by andrey-helldar** [comment]
Thanks for PR 🤝

**Pull request merged**
