### PR TITLE
[10.x] Minor fix for structure correction of the `laravel-lang/lang`

### PR DESCRIPTION
**Pull request by andrey-helldar**
See https://github.com/Laravel-Lang/lang/pull/1762

### CODE REVIEW

**Comment by luisprmat** [comment]
You have abandoned this PR 😢!

**Comment by andrey-helldar** [comment]
@luisprmat, no. We have a very hot summer in St. Petersburg. Last time it was 10 years ago. I don't feel very well in the heat. Therefore, the release of the new version was postponed a little.

In addition, I am doing a complete refactoring of the project to add new functionality.

**Comment by mohamedsabil83** [comment]
Hey @andrey-helldar, any news or maybe ETA?

**Comment by andrey-helldar** [comment]
@mohamedsabil83, @luisprmat, hi guys!

Sorry, I was very busy at my main job. Thanks to this, I created a project Cashier: https://github.com/andrey-helldar/cashier

Yesterday I started creating contracts for the publisher. 

In the next 1-2 weeks I will try to rewrite the project and release it for release.

Thanks for your support!

**Comment by mohamedsabil83** [comment]
Good news @andrey-helldar will wait for it. Also, I am concerned with the cashier package. I'll take a look later.

**Comment by andrey-helldar** [comment]
@mohamedsabil83, Cashier is a provider for payment systems.
You can connect a driver to it to work with any bank. I tried to write simple and understandable instructions for their development with examples.

But it's better to talk about this in the Cashier project 😊

**Pull request merged**
